name: word2vec
channels:
  - defaults
dependencies:
  - ca-certificates=2021.9.30
  - certifi=2021.10.8
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.7.11
  - setuptools=58.0.4
  - sqlite=3.36.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.0
  - wincertstore=0.2
  - pip:
    - click==8.0.3
    - colorama==0.4.4
    - importlib-metadata==4.8.1
    - joblib==1.1.0
    - nltk==3.6.5
    - numpy==1.21.2
    - regex==2021.10.8
    - scipy==1.7.1
    - tqdm==4.62.3
    - typing-extensions==3.10.0.2
    - zipp==3.6.0
